environment:
  language: ruby
  language_versions: 1.9.3_p392
  build:
    before: echo nothing
    run:
      one: echo "somfin"
      two: echo "somfin else"
  notifictions:
    - email:
      - gblike@groupon.com
