#! /bin/sh 
SNAPSHOT_NAME="mycoolapp"
gtar  -cvzf $SNAPSHOT_NAME.tar.gz roller-configs/mycoolapp_config  

curl --upload-file $SNAPSHOT_NAME.tar.gz http://config/package/$SNAPSHOT_NAME.tar.gz
rm $SNAPSHOT_NAME.tar.gz
echo uploaded $SNAPSHOT_NAME
